import React, {Component} from 'react';
import InfoBlock from './InfoBlock';

/**
 * Main content for About page.
 * This Component should be passed in as a Child Component for SimpleLayout
 */
class About extends Component {

    render() {
        return (
            <div className="container-fluid">
                <div className="jumbotron">
                    <h1>MetProt</h1>
                </div>

                <div className="row">
                    <div className="col-sm-12 col-md-12 main">
                        <div className="row placeholders">
                            <div className="col-sm-8 placeholder text-left">
                                <h2>Introduction:</h2>
                                <p>The rapid development of analytical technologies has drastically increased the amount of data generated by both proteomics and metabolomics experiments. Both proteins and metabolites are essential building blocks of cellular processes that collaboratively formulate biological pathways. However, many large datasets of either proteins or metabolites are often fragmented and rarely integrated. We have addressed this data science challenge via developing an integrated platform for collective analyses of protein data with metabolite information.</p>
                            </div>
                            <div className="col-xs-8 col-sm-4 placeholder">
                                <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="240" height="240" className="img-responsive" alt="img3"></img>
                            </div>
                        </div>
                        <div className="row placeholders">
                            <div className="col-sm-8 placeholder text-left">
                                <h2>Approach: </h2>
                                <p>We have formulated our strategy based on the considerations where metabolome meets proteome at the following intersections: their shared biological and cellular pathways, chemical and biochemical reactions, post-translational modifications, metabolites as ligand for protein-based receptors, and metabolites-based transcriptional regulation. Importantly, both are characterized by mass spectrometry. Accordingly, MetProt consists of a Wiki user interface and a distributed system architecture; it fetches information via application programming interfaces (APIs), retrieving data from multiple resources including biological pathways from Reactome/KEGG PATHWAY, chemical reactions from UniProt/HMDB, PTMs from dbPTM/PhosphoSitePlus, and ligand and drug information from KEGG LIGAND/DrugBank. Subsequently, the collected information are used to construct a network of direct and indirect interactions between proteins and metabolites. In addition, biological and chemical functional annotations for proteins and metabolites are retrieved from COPaKB/Gene Wiki and MetaboLights/ChEBI. MetProt will be hosted on Amazon Web Services (AWS), enabling users to perform these analyses on the cloud and generate integrated reports, including a table view of protein-metabolite interactions, and functional annotations as well as graphical views of networks and pathways.</p>
                            </div>
                            <div className="col-xs-8 col-sm-4 placeholder">
                                <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="240" height="240" className="img-responsive" alt="img3"></img>
                            </div>
                        </div>
                        <div className="row placeholders">
                            <div className="col-sm-8 placeholder text-left">
                                <h2>Summary: </h2>
                                <p>We are establishing a cloud-based platform, MetProt, for quantifying, triaging and analyzing omics datasets, finding existing as well as novel connections between proteins and metabolites, annotating molecular functions, and providing biomedical insights.</p>
                            </div>
                            <div className="col-xs-8 col-sm-4 placeholder">
                                <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="240" height="240" className="img-responsive" alt="img3"></img>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        )
    }


}

export default About;